// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using TL.DataAccess.Models;

namespace TL.Travel.DataAccess.Base
{
    public partial class BaseTLTravelDbContext : DbContext
    {
        public BaseTLTravelDbContext()
        {
            //this.Database.EnsureCreated();
        }

        public BaseTLTravelDbContext(DbContextOptions options)
            : base(options)
        {
            //this.Database.EnsureCreated();
        }

        public virtual DbSet<Agent> Agents { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Extra> Extras { get; set; }
        public virtual DbSet<FeedingType> FeedingTypes { get; set; }
        public virtual DbSet<Hotel> Hotels { get; set; }
        public virtual DbSet<HotelExtra> HotelExtras { get; set; }
        public virtual DbSet<HotelFeedingType> HotelFeedingTypes { get; set; }
        public virtual DbSet<HotelPhoto> HotelPhotos { get; set; }
        public virtual DbSet<HotelRoom> HotelRooms { get; set; }
        public virtual DbSet<HotelRoomExtra> HotelRoomExtras { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Operator> Operators { get; set; }
        public virtual DbSet<PaymentChannel> PaymentChannels { get; set; }
        public virtual DbSet<PaymentType> PaymentTypes { get; set; }
        public virtual DbSet<Reservation> Reservations { get; set; }
        public virtual DbSet<ReservationPayment> ReservationPayments { get; set; }
        public virtual DbSet<ReservationRoom> ReservationRooms { get; set; }
        public virtual DbSet<ReservationStatus> ReservationStatuses { get; set; }
        public virtual DbSet<RoomPhoto> RoomPhotos { get; set; }


        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
