// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TL.DataAccess.Models
{
    public partial class Extra
    {
        public Extra()
        {
            HotelExtras = new HashSet<HotelExtra>();
            HotelRoomExtras = new HashSet<HotelRoomExtra>();
        }

        [Key]
        public int Id { get; set; }

        [Required]
        [StringLength(200)]
        [Unicode(false)]
        public string Name { get; set; }

        public bool IsActive { get; set; }

        [Required]
        [StringLength(200)]
        [Unicode(false)]
        public string CreatedBy { get; set; }

        public DateTime CreatedOn { get; set; }

        [StringLength(200)]
        [Unicode(false)]
        public string UpdatedBy { get; set; }

        public DateTime? UpdatedOn { get; set; }

        [InverseProperty("Extras")]
        public virtual ICollection<HotelExtra> HotelExtras { get; set; }

        [InverseProperty("Extras")]
        public virtual ICollection<HotelRoomExtra> HotelRoomExtras { get; set; }
    }
}
