// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TL.DataAccess.Models
{
    public partial class FeedingType
    {
        public FeedingType()
        {
            HotelFeedingTypes = new HashSet<HotelFeedingType>();
            ReservationRooms = new HashSet<ReservationRoom>();
        }

        [Key]
        public int Id { get; set; }

        [StringLength(50)]
        [Unicode(false)]
        public string Code { get; set; }

        [Required]
        [StringLength(200)]
        [Unicode(false)]
        public string Name { get; set; }

        public bool IsActive { get; set; }

        [Required]
        [StringLength(200)]
        [Unicode(false)]
        public string CreatedBy { get; set; }

        public DateTime CreatedOn { get; set; }

        [StringLength(200)]
        [Unicode(false)]
        public string UpdatedBy { get; set; }

        public DateTime? UpdatedOn { get; set; }

        [InverseProperty("FeedingType")]
        public virtual ICollection<HotelFeedingType> HotelFeedingTypes { get; set; }

        [InverseProperty("FeedingType")]
        public virtual ICollection<ReservationRoom> ReservationRooms { get; set; }
    }
}
