// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TL.DataAccess.Models
{
    public partial class HotelRoom
    {
        public HotelRoom()
        {
            HotelRoomExtras = new HashSet<HotelRoomExtra>();
            ReservationRooms = new HashSet<ReservationRoom>();
            RoomPhotos = new HashSet<RoomPhoto>();
        }

        [Key]
        public int Id { get; set; }

        public int HotelId { get; set; }

        [Required]
        [StringLength(200)]
        [Unicode(false)]
        public string Name { get; set; }

        public decimal Price { get; set; }

        [Unicode(false)]
        public string Description { get; set; }

        public bool IsActive { get; set; }

        public int? MaxAdults { get; set; }

        public int? MaxChildren { get; set; }

        public int? MaxBabies { get; set; }

        [Required]
        [StringLength(200)]
        [Unicode(false)]
        public string CreatedBy { get; set; }

        public DateTime CreatedOn { get; set; }

        [StringLength(200)]
        [Unicode(false)]
        public string UpdatedBy { get; set; }

        public DateTime? UpdatedOn { get; set; }

        [ForeignKey("HotelId")]
        [InverseProperty("HotelRooms")]
        public virtual Hotel Hotel { get; set; }

        [InverseProperty("HotelRoom")]
        public virtual ICollection<HotelRoomExtra> HotelRoomExtras { get; set; }

        [InverseProperty("HotelRoom")]
        public virtual ICollection<ReservationRoom> ReservationRooms { get; set; }

        [InverseProperty("HotelRoom")]
        public virtual ICollection<RoomPhoto> RoomPhotos { get; set; }
    }
}
