// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TL.DataAccess.Models
{
    public partial class Hotel
    {
        public Hotel()
        {
            HotelExtras = new HashSet<HotelExtra>();
            HotelFeedingTypes = new HashSet<HotelFeedingType>();
            HotelPhotos = new HashSet<HotelPhoto>();
            HotelRooms = new HashSet<HotelRoom>();
            Reservations = new HashSet<Reservation>();
        }

        [Key]
        public int Id { get; set; }

        [Required]
        [StringLength(200)]
        [Unicode(false)]
        public string Name { get; set; }

        public int Stars { get; set; }

        [Required]
        [StringLength(500)]
        [Unicode(false)]
        public string Contacts { get; set; }

        public bool IsTemporaryClosed { get; set; }

        public int LocationId { get; set; }

        public int PartnerId { get; set; }

        public bool IsActive { get; set; }

        [Required]
        [StringLength(200)]
        [Unicode(false)]
        public string CreatedBy { get; set; }

        public DateTime CreatedOn { get; set; }

        [StringLength(200)]
        [Unicode(false)]
        public string UpdatedBy { get; set; }

        public DateTime? UpdatedOn { get; set; }

        [ForeignKey("LocationId")]
        [InverseProperty("Hotels")]
        public virtual Location Location { get; set; }

        [ForeignKey("PartnerId")]
        [InverseProperty("Hotels")]
        public virtual Agent Partner { get; set; }

        [InverseProperty("Hotel")]
        public virtual ICollection<HotelExtra> HotelExtras { get; set; }

        [InverseProperty("Hotel")]
        public virtual ICollection<HotelFeedingType> HotelFeedingTypes { get; set; }

        [InverseProperty("Hotel")]
        public virtual ICollection<HotelPhoto> HotelPhotos { get; set; }

        [InverseProperty("Hotel")]
        public virtual ICollection<HotelRoom> HotelRooms { get; set; }

        [InverseProperty("Hotel")]
        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}
