// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TL.DataAccess.Models
{
    public partial class HotelExtra
    {
        [Key]
        public int HotelId { get; set; }

        [Key]
        public int ExtrasId { get; set; }

        public bool IsActive { get; set; }

        [Required]
        [StringLength(200)]
        [Unicode(false)]
        public string CreatedBy { get; set; }

        public DateTime CreatedOn { get; set; }

        [StringLength(200)]
        [Unicode(false)]
        public string UpdatedBy { get; set; }

        public DateTime? UpdatedOn { get; set; }

        [ForeignKey("ExtrasId")]
        [InverseProperty("HotelExtras")]
        public virtual Extra Extras { get; set; }

        [ForeignKey("HotelId")]
        [InverseProperty("HotelExtras")]
        public virtual Hotel Hotel { get; set; }
    }
}
