// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TL.DataAccess.Models
{
    public partial class HotelRoomExtra
    {
        [Key]
        public int HotelRoomId { get; set; }

        [Key]
        public int ExtrasId { get; set; }

        public bool IsActive { get; set; }

        [Required]
        [StringLength(200)]
        [Unicode(false)]
        public string CreatedBy { get; set; }

        public DateTime CreatedOn { get; set; }

        [StringLength(200)]
        [Unicode(false)]
        public string UpdatedBy { get; set; }

        public DateTime? UpdatedOn { get; set; }

        [ForeignKey("ExtrasId")]
        [InverseProperty("HotelRoomExtras")]
        public virtual Extra Extras { get; set; }

        [ForeignKey("HotelRoomId")]
        [InverseProperty("HotelRoomExtras")]
        public virtual HotelRoom HotelRoom { get; set; }
    }
}
