// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TL.DataAccess.Models
{
    [Table("HOTEL_PHOTOS")]
    [Index("HotelId", Name = "HOTELPHOTOS_HOTEL_ID_IDX")]
    public partial class HotelPhoto
    {
        [Key]
        public int Id { get; set; }

        public int HotelId { get; set; }

        [Required]
        public byte[] Photo { get; set; }

        public bool IsActive { get; set; }

        [Required]
        [StringLength(200)]
        [Unicode(false)]
        public string CreatedBy { get; set; }

        public DateTime CreatedOn { get; set; }

        [StringLength(200)]
        [Unicode(false)]
        public string UpdatedBy { get; set; }

        public DateTime? UpdatedOn { get; set; }

        [ForeignKey("HotelId")]
        [InverseProperty("HotelPhotos")]
        public virtual Hotel Hotel { get; set; }
    }
}
