// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TL.DataAccess.Models
{
    public partial class Operator
    {
        public Operator()
        {
            Reservations = new HashSet<Reservation>();
        }

        [Key]
        public int Id { get; set; }

        [Required]
        [StringLength(200)]
        [Unicode(false)]
        public string Name { get; set; }

        [Required]
        [StringLength(200)]
        [Unicode(false)]
        public string Email { get; set; }

        [Required]
        [StringLength(100)]
        [Unicode(false)]
        public string Password { get; set; }

        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Phone { get; set; }

        [Required]
        [StringLength(500)]
        [Unicode(false)]
        public string Address { get; set; }

        public bool IsActive { get; set; }

        [Required]
        [StringLength(200)]
        [Unicode(false)]
        public string CreatedBy { get; set; }

        public DateTime CreatedOn { get; set; }

        [StringLength(200)]
        [Unicode(false)]
        public string UpdatedBy { get; set; }

        public DateTime? UpdatedOn { get; set; }

        [InverseProperty("Operator")]
        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}
