// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TL.DataAccess.Models
{
    [Table("PAYMENT_TYPE")]
    [Index("Name", Name = "PAYMENTTYPES_NAME_UK", IsUnique = true)]
    public partial class PaymentType
    {
        public PaymentType()
        {
            ReservationPayments = new HashSet<ReservationPayment>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }

        [Required]
        [StringLength(200)]
        [Unicode(false)]
        public string Name { get; set; }

        public bool IsActive { get; set; }

        [Required]
        [StringLength(200)]
        [Unicode(false)]
        public string CreatedBy { get; set; }

        public DateTime CreatedOn { get; set; }

        [StringLength(200)]
        [Unicode(false)]
        public string UpdatedBy { get; set; }

        public DateTime? UpdatedOn { get; set; }

        [InverseProperty("PaymentType")]
        public virtual ICollection<ReservationPayment> ReservationPayments { get; set; }
    }
}
