// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TL.DataAccess.Models
{
    public partial class ReservationPayment
    {
        [Key]
        public int Id { get; set; }

        public int ReservationId { get; set; }

        public DateTime DueDate { get; set; }

        public int PaymentTypeId { get; set; }

        public int PaymentChannelId { get; set; }

        public decimal Amount { get; set; }

        public bool IsPaid { get; set; }

        public bool IsActive { get; set; }

        [Required]
        [StringLength(200)]
        [Unicode(false)]
        public string CreatedBy { get; set; }

        public DateTime CreatedOn { get; set; }

        [StringLength(200)]
        [Unicode(false)]
        public string UpdatedBy { get; set; }

        public DateTime? UpdatedOn { get; set; }

        [ForeignKey("PaymentChannelId")]
        [InverseProperty("ReservationPayments")]
        public virtual PaymentChannel PaymentChannel { get; set; }

        [ForeignKey("PaymentTypeId")]
        [InverseProperty("ReservationPayments")]
        public virtual PaymentType PaymentType { get; set; }

        [ForeignKey("ReservationId")]
        [InverseProperty("ReservationPayments")]
        public virtual Reservation Reservation { get; set; }
    }
}
