// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TL.DataAccess.Models
{
    public partial class ReservationRoom
    {
        public int Adults { get; set; }

        public int Children { get; set; }

        public int Babies { get; set; }

        public decimal Price { get; set; }

        [Key]
        public int Id { get; set; }

        public int HotelRoomId { get; set; }

        public int ReservationId { get; set; }

        public int FeedingTypeId { get; set; }

        [ForeignKey("FeedingTypeId")]
        [InverseProperty("ReservationRooms")]
        public virtual FeedingType FeedingType { get; set; }

        [ForeignKey("HotelRoomId")]
        [InverseProperty("ReservationRooms")]
        public virtual HotelRoom HotelRoom { get; set; }

        [ForeignKey("ReservationId")]
        [InverseProperty("ReservationRooms")]
        public virtual Reservation Reservation { get; set; }
    }
}
