// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TL.DataAccess.Models
{
    public partial class Reservation
    {
        public Reservation()
        {
            ReservationPayments = new HashSet<ReservationPayment>();
            ReservationRooms = new HashSet<ReservationRoom>();
        }

        [Key]
        public int Id { get; set; }

        public int HotelId { get; set; }

        public int ClientId { get; set; }

        public int OperatorId { get; set; }

        public int ReservationStatusId { get; set; }

        public DateTime DateFrom { get; set; }

        public DateTime DateTo { get; set; }

        [Unicode(false)]
        public string CustomerNotes { get; set; }

        public decimal TotalPrice { get; set; }

        public bool IsActive { get; set; }

        [Required]
        [StringLength(200)]
        [Unicode(false)]
        public string CreatedBy { get; set; }

        public DateTime CreatedOn { get; set; }

        [StringLength(200)]
        [Unicode(false)]
        public string UpdatedBy { get; set; }

        public DateTime? UpdatedOn { get; set; }

        [ForeignKey("ClientId")]
        [InverseProperty("Reservations")]
        public virtual Client Client { get; set; }

        [ForeignKey("HotelId")]
        [InverseProperty("Reservations")]
        public virtual Hotel Hotel { get; set; }

        [ForeignKey("OperatorId")]
        [InverseProperty("Reservations")]
        public virtual Operator Operator { get; set; }

        [ForeignKey("ReservationStatusId")]
        [InverseProperty("Reservations")]
        public virtual ReservationStatus ReservationStatus { get; set; }

        [InverseProperty("Reservation")]
        public virtual ICollection<ReservationPayment> ReservationPayments { get; set; }

        [InverseProperty("Reservation")]
        public virtual ICollection<ReservationRoom> ReservationRooms { get; set; }
    }
}
