// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using TL.DataAccess.Models;
using TL.Travel.DataAccess.Base;

namespace TL.Travel.DataAccess.Db;

public partial class TLTravelDbContext : BaseTLTravelDbContext
{
    public TLTravelDbContext()
        : base()
    {
        this.Database.EnsureCreated();
    }

    public TLTravelDbContext(DbContextOptions<TLTravelDbContext> options)
        : base(options)
    {
        this.Database.EnsureCreated();
    }


    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Agent>(entity =>
        {
            entity.ToTable("AGENTS");

            entity.HasIndex(e => e.Name, "PARTNER_NAME_UK").IsUnique();

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.ComissionPercent)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("COMISSION_PERCENT");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("CREATED_BY");
            entity.Property(e => e.CreatedOn).HasColumnName("CREATED_ON");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("IS_ACTIVE");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("NAME");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("UPDATED_BY");
            entity.Property(e => e.UpdatedOn).HasColumnName("UPDATED_ON");
        });

        modelBuilder.Entity<Client>(entity =>
        {
            entity.ToTable("CLIENTS");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("CREATED_BY");
            entity.Property(e => e.CreatedOn).HasColumnName("CREATED_ON");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("EMAIL");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("IS_ACTIVE");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("NAME");
            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("PHONE");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("UPDATED_BY");
            entity.Property(e => e.UpdatedOn).HasColumnName("UPDATED_ON");
        });

        modelBuilder.Entity<Extra>(entity =>
        {
            entity.ToTable("EXTRAS");

            entity.HasIndex(e => e.Name, "EXTRAS_NAME_UK").IsUnique();

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("CREATED_BY");
            entity.Property(e => e.CreatedOn).HasColumnName("CREATED_ON");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("IS_ACTIVE");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("NAME");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("UPDATED_BY");
            entity.Property(e => e.UpdatedOn).HasColumnName("UPDATED_ON");
        });

        modelBuilder.Entity<FeedingType>(entity =>
        {
            entity.ToTable("FEEDING_TYPES");

            entity.HasIndex(e => e.Name, "FEEDINGTYPES_NAME_UK").IsUnique();

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Code)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("CODE");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("CREATED_BY");
            entity.Property(e => e.CreatedOn).HasColumnName("CREATED_ON");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("IS_ACTIVE");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("NAME");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("UPDATED_BY");
            entity.Property(e => e.UpdatedOn).HasColumnName("UPDATED_ON");
        });

        modelBuilder.Entity<Hotel>(entity =>
        {
            entity.ToTable("HOTELS");

            entity.HasIndex(e => e.LocationId, "HOTEL_LOCATION_ID_IDX");

            entity.HasIndex(e => e.Name, "HOTEL_NAME_UK").IsUnique();

            entity.HasIndex(e => e.PartnerId, "HOTEL_PARTNER_ID_IDX");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Contacts)
                .IsRequired()
                .HasMaxLength(500)
                .IsUnicode(false)
                .HasColumnName("CONTACTS");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("CREATED_BY");
            entity.Property(e => e.CreatedOn).HasColumnName("CREATED_ON");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("IS_ACTIVE");
            entity.Property(e => e.IsTemporaryClosed)
                .HasDefaultValue(false)
                .HasColumnName("IS_TEMPORARY_CLOSED");
            entity.Property(e => e.LocationId).HasColumnName("LOCATION_ID");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("NAME");
            entity.Property(e => e.PartnerId).HasColumnName("PARTNER_ID");
            entity.Property(e => e.Stars).HasColumnName("STARS");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("UPDATED_BY");
            entity.Property(e => e.UpdatedOn).HasColumnName("UPDATED_ON");

            entity.HasOne(d => d.Location).WithMany(p => p.Hotels)
                .HasForeignKey(d => d.LocationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("HOTEL_LOCATION_FK");

            entity.HasOne(d => d.Partner).WithMany(p => p.Hotels)
                .HasForeignKey(d => d.PartnerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("HOTEL_AGENT_FK");
        });

        modelBuilder.Entity<HotelExtra>(entity =>
        {
            entity.HasKey(e => new { e.ExtrasId, e.HotelId }).HasName("HOTELEXTRAS_PK");

            entity.ToTable("HOTEL_EXTRAS");

            entity.HasIndex(e => e.ExtrasId, "HOTELEXTRAS_EXTRAS_ID_IDX");

            entity.HasIndex(e => e.HotelId, "HOTELEXTRAS_HOTEL_ID_IDX");

            entity.Property(e => e.ExtrasId).HasColumnName("EXTRAS_ID");
            entity.Property(e => e.HotelId).HasColumnName("HOTEL_ID");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("CREATED_BY");
            entity.Property(e => e.CreatedOn).HasColumnName("CREATED_ON");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("IS_ACTIVE");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("UPDATED_BY");
            entity.Property(e => e.UpdatedOn).HasColumnName("UPDATED_ON");

            entity.HasOne(d => d.Extras).WithMany(p => p.HotelExtras)
                .HasForeignKey(d => d.ExtrasId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("HOTEXTRA_EXTRAS_FK");

            entity.HasOne(d => d.Hotel).WithMany(p => p.HotelExtras)
                .HasForeignKey(d => d.HotelId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("HOTEXTRA_HOTEL_FK");
        });

        modelBuilder.Entity<HotelFeedingType>(entity =>
        {
            entity.HasKey(e => new { e.HotelId, e.FeedingTypeId }).HasName("HOTELFEEDINGTYPES_PK");

            entity.ToTable("HOTEL_FEEDING_TYPES");

            entity.HasIndex(e => e.HotelId, "HOTELFEEDINGTYPES_HOTEL_ID_IDX");

            entity.HasIndex(e => e.FeedingTypeId, "HOTFEEDINGTYP_FEEDTYPE_ID_IDX");

            entity.Property(e => e.HotelId).HasColumnName("HOTEL_ID");
            entity.Property(e => e.FeedingTypeId).HasColumnName("FEEDING_TYPE_ID");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("CREATED_BY");
            entity.Property(e => e.CreatedOn).HasColumnName("CREATED_ON");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("IS_ACTIVE");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("UPDATED_BY");
            entity.Property(e => e.UpdatedOn).HasColumnName("UPDATED_ON");

            entity.HasOne(d => d.FeedingType).WithMany(p => p.HotelFeedingTypes)
                .HasForeignKey(d => d.FeedingTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("HOTFEDTYP_FEEDINGTYPE_FK");

            entity.HasOne(d => d.Hotel).WithMany(p => p.HotelFeedingTypes)
                .HasForeignKey(d => d.HotelId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("HOTFEDTYP_HOTEL_FK");
        });

        modelBuilder.Entity<HotelPhoto>(entity =>
        {
            entity.ToTable("HOTEL_PHOTOS");

            entity.HasIndex(e => e.HotelId, "HOTELPHOTOS_HOTEL_ID_IDX");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("CREATED_BY");
            entity.Property(e => e.CreatedOn).HasColumnName("CREATED_ON");
            entity.Property(e => e.HotelId).HasColumnName("HOTEL_ID");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("IS_ACTIVE");
            entity.Property(e => e.Photo)
                .IsRequired()
                .HasColumnName("PHOTO");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("UPDATED_BY");
            entity.Property(e => e.UpdatedOn).HasColumnName("UPDATED_ON");

            entity.HasOne(d => d.Hotel).WithMany(p => p.HotelPhotos)
                .HasForeignKey(d => d.HotelId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("HOTELPHOTOS_HOTEL_FK");
        });

        modelBuilder.Entity<HotelRoom>(entity =>
        {
            entity.ToTable("HOTEL_ROOMS");

            entity.HasIndex(e => e.HotelId, "HOTELROOM_HOTEL_ID_IDX");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("CREATED_BY");
            entity.Property(e => e.CreatedOn).HasColumnName("CREATED_ON");
            entity.Property(e => e.Description)
                .IsUnicode(false)
                .HasColumnName("DESCRIPTION");
            entity.Property(e => e.HotelId).HasColumnName("HOTEL_ID");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("IS_ACTIVE");
            entity.Property(e => e.MaxAdults).HasColumnName("MAX_ADULTS");
            entity.Property(e => e.MaxBabies).HasColumnName("MAX_BABIES");
            entity.Property(e => e.MaxChildren).HasColumnName("MAX_CHILDREN");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("NAME");
            entity.Property(e => e.Price)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("PRICE");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("UPDATED_BY");
            entity.Property(e => e.UpdatedOn).HasColumnName("UPDATED_ON");

            entity.HasOne(d => d.Hotel).WithMany(p => p.HotelRooms)
                .HasForeignKey(d => d.HotelId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("HOTELROOM_HOTEL_FK");
        });

        modelBuilder.Entity<HotelRoomExtra>(entity =>
        {
            entity.HasKey(e => new { e.ExtrasId, e.HotelRoomId }).HasName("HOTEL_ROOM_EXTRAS_PK");

            entity.ToTable("HOTEL_ROOM_EXTRAS");

            entity.HasIndex(e => e.ExtrasId, "HOTEL_ROOM_EXTRAS_EXTRAS_ID_IDX");

            entity.HasIndex(e => e.HotelRoomId, "HOTROOMEXTRAS_HOTROOM_ID_IDX");

            entity.Property(e => e.ExtrasId).HasColumnName("EXTRAS_ID");
            entity.Property(e => e.HotelRoomId).HasColumnName("HOTELROOM_ID");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("CREATED_BY");
            entity.Property(e => e.CreatedOn).HasColumnName("CREATED_ON");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("IS_ACTIVE");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("UPDATED_BY");
            entity.Property(e => e.UpdatedOn).HasColumnName("UPDATED_ON");

            entity.HasOne(d => d.Extras).WithMany(p => p.HotelRoomExtras)
                .HasForeignKey(d => d.ExtrasId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("HOTROOMEXT_EXTRAS_FK");

            entity.HasOne(d => d.HotelRoom).WithMany(p => p.HotelRoomExtras)
                .HasForeignKey(d => d.HotelRoomId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("HOTROOMEXT_HOTELROOM_FK");
        });

        modelBuilder.Entity<Location>(entity =>
        {
            entity.ToTable("LOCATIONS");

            entity.HasIndex(e => e.Name, "LOCATIONS_NAME_UK").IsUnique();

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("CREATED_BY");
            entity.Property(e => e.CreatedOn).HasColumnName("CREATED_ON");
            entity.Property(e => e.IsAbroad).HasColumnName("IS_ABROAD");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("IS_ACTIVE");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("NAME");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("UPDATED_BY");
            entity.Property(e => e.UpdatedOn).HasColumnName("UPDATED_ON");
        });

        modelBuilder.Entity<Operator>(entity =>
        {
            entity.ToTable("OPERATORS");

            entity.HasIndex(e => e.Name, "OPERATOR_NAME_UK").IsUnique();

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Address)
                .IsRequired()
                .HasMaxLength(500)
                .IsUnicode(false)
                .HasColumnName("ADDRESS");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("CREATED_BY");
            entity.Property(e => e.CreatedOn).HasColumnName("CREATED_ON");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("EMAIL");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("IS_ACTIVE");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("NAME");
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("PASSWORD");
            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("PHONE");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("UPDATED_BY");
            entity.Property(e => e.UpdatedOn).HasColumnName("UPDATED_ON");
        });

        modelBuilder.Entity<PaymentChannel>(entity =>
        {
            entity.ToTable("PAYMENT_CHANNELS");

            entity.HasIndex(e => e.Name, "PAYMENT_CHANNELS_NAME_UK").IsUnique();

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("CREATED_BY");
            entity.Property(e => e.CreatedOn).HasColumnName("CREATED_ON");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("IS_ACTIVE");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("NAME");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("UPDATED_BY");
            entity.Property(e => e.UpdatedOn).HasColumnName("UPDATED_ON");
        });

        modelBuilder.Entity<PaymentType>(entity =>
        {
            entity.ToTable("PAYMENT_TYPES");

            entity.HasIndex(e => e.Name, "PAYMENTTYPES_NAME_UK").IsUnique();

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("CREATED_BY");
            entity.Property(e => e.CreatedOn).HasColumnName("CREATED_ON");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("IS_ACTIVE");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("NAME");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("UPDATED_BY");
            entity.Property(e => e.UpdatedOn).HasColumnName("UPDATED_ON");
        });

        modelBuilder.Entity<Reservation>(entity =>
        {
            entity.ToTable("RESERVATIONS");

            entity.HasIndex(e => e.ClientId, "RESERVATION_CLIENT_ID_IDX");

            entity.HasIndex(e => e.HotelId, "RESERVATION_HOTEL_ID_IDX");

            entity.HasIndex(e => e.OperatorId, "RESERVATION_OPERATOR_ID_IDX");

            entity.HasIndex(e => e.ReservationStatusId, "RES_RESSTATUS_ID_IDX");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.ClientId).HasColumnName("CLIENT_ID");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("CREATED_BY");
            entity.Property(e => e.CreatedOn).HasColumnName("CREATED_ON");
            entity.Property(e => e.CustomerNotes)
                .IsUnicode(false)
                .HasColumnName("CUSTOMER_NOTES");
            entity.Property(e => e.DateFrom).HasColumnName("DATE_FROM");
            entity.Property(e => e.DateTo).HasColumnName("DATE_TO");
            entity.Property(e => e.HotelId).HasColumnName("HOTEL_ID");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("IS_ACTIVE");
            entity.Property(e => e.OperatorId).HasColumnName("OPERATOR_ID");
            entity.Property(e => e.ReservationStatusId).HasColumnName("RESERVATION_STATUS_ID");
            entity.Property(e => e.TotalPrice)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("TOTAL_PRICE");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("UPDATED_BY");
            entity.Property(e => e.UpdatedOn).HasColumnName("UPDATED_ON");

            entity.HasOne(d => d.Client).WithMany(p => p.Reservations)
                .HasForeignKey(d => d.ClientId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("RESERVATION_CLIENT_FK");

            entity.HasOne(d => d.Hotel).WithMany(p => p.Reservations)
                .HasForeignKey(d => d.HotelId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("RESERVATION_HOTEL_FK");

            entity.HasOne(d => d.Operator).WithMany(p => p.Reservations)
                .HasForeignKey(d => d.OperatorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("RESERVATION_OPERATOR_FK");

            entity.HasOne(d => d.ReservationStatus).WithMany(p => p.Reservations)
                .HasForeignKey(d => d.ReservationStatusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("RES_RESSTATUS_FK");
        });

        modelBuilder.Entity<ReservationPayment>(entity =>
        {
            entity.ToTable("RESERVATION_PAYMENTS");

            entity.HasIndex(e => e.PaymentTypeId, "IX_RESERVATIONPAYMENT_PAYMENT_TYPE_ID");

            entity.HasIndex(e => e.PaymentChannelId, "RESPAYMENT_PAYCHAN_ID_IDX");

            entity.HasIndex(e => e.ReservationId, "RESPAYMENT_RES_ID_IDX");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Amount)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("AMOUNT");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("CREATED_BY");
            entity.Property(e => e.CreatedOn).HasColumnName("CREATED_ON");
            entity.Property(e => e.DueDate).HasColumnName("DUE_DATE");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("IS_ACTIVE");
            entity.Property(e => e.IsPaid).HasColumnName("IS_PAID");
            entity.Property(e => e.PaymentTypeId).HasColumnName("PAYMENT_TYPE_ID");
            entity.Property(e => e.PaymentChannelId).HasColumnName("PAYMENTCHANNEL_ID");
            entity.Property(e => e.ReservationId).HasColumnName("RESERVATION_ID");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("UPDATED_BY");
            entity.Property(e => e.UpdatedOn).HasColumnName("UPDATED_ON");

            entity.HasOne(d => d.PaymentType).WithMany(p => p.ReservationPayments)
                .HasForeignKey(d => d.PaymentTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("RESPAYMENT_PAYMENTTYPE_FK");

            entity.HasOne(d => d.PaymentChannel).WithMany(p => p.ReservationPayments)
                .HasForeignKey(d => d.PaymentChannelId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("RESPAYMENT_PAYMENTCHANNEL_FK");

            entity.HasOne(d => d.Reservation).WithMany(p => p.ReservationPayments)
                .HasForeignKey(d => d.ReservationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("RESPAYMENT_RESERVATION_FK");
        });

        modelBuilder.Entity<ReservationRoom>(entity =>
        {
            entity.ToTable("RESERVATION_ROOMS");

            entity.HasIndex(e => e.FeedingTypeId, "RESEROOMS_FEEDINGTYPE_ID_IDX");

            entity.HasIndex(e => e.HotelRoomId, "RESROOMS_HOTELROOM_ID_IDX");

            entity.HasIndex(e => e.ReservationId, "RESROOMS_RESERVATION_ID_IDX");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Adults).HasColumnName("ADULTS");
            entity.Property(e => e.Babies).HasColumnName("BABIES");
            entity.Property(e => e.Children).HasColumnName("CHILDREN");
            entity.Property(e => e.FeedingTypeId).HasColumnName("FEEDING_TYPE_ID");
            entity.Property(e => e.HotelRoomId).HasColumnName("HOTEL_ROOM_ID");
            entity.Property(e => e.Price)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("PRICE");
            entity.Property(e => e.ReservationId).HasColumnName("RESERVATION_ID");

            entity.HasOne(d => d.FeedingType).WithMany(p => p.ReservationRooms)
                .HasForeignKey(d => d.FeedingTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("RESROOM_FEEDING_TYPE_FK");

            entity.HasOne(d => d.HotelRoom).WithMany(p => p.ReservationRooms)
                .HasForeignKey(d => d.HotelRoomId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("RESROOM_HOTEL_ROOM_FK");

            entity.HasOne(d => d.Reservation).WithMany(p => p.ReservationRooms)
                .HasForeignKey(d => d.ReservationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("RESROOM_RESERVATION_FK");
        });

        modelBuilder.Entity<ReservationStatus>(entity =>
        {
            entity.ToTable("RESERVATION_STATUSES");

            entity.HasIndex(e => e.Code, "RESERVATION_STATUS_CODE_UK").IsUnique();

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("CODE");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("CREATED_BY");
            entity.Property(e => e.CreatedOn).HasColumnName("CREATED_ON");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("IS_ACTIVE");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("NAME");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("UPDATED_BY");
            entity.Property(e => e.UpdatedOn).HasColumnName("UPDATED_ON");
        });

        modelBuilder.Entity<RoomPhoto>(entity =>
        {
            entity.ToTable("ROOM_PHOTOS");

            entity.HasIndex(e => e.HotelRoomId, "ROOMPHOTOS_HOTELROOM_ID_IDX");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("CREATED_BY");
            entity.Property(e => e.CreatedOn).HasColumnName("CREATED_ON");
            entity.Property(e => e.HotelRoomId).HasColumnName("HOTEL_ROOM_ID");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("IS_ACTIVE");
            entity.Property(e => e.Photo)
                .IsRequired()
                .HasColumnName("PHOTO");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("UPDATED_BY");
            entity.Property(e => e.UpdatedOn).HasColumnName("UPDATED_ON");

            entity.HasOne(d => d.HotelRoom).WithMany(p => p.RoomPhotos)
                .HasForeignKey(d => d.HotelRoomId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("ROOM_PHOTOS_HOTELROOM_FK");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
